### PR TITLE
Add rake tasks to non-Rails projects

### PR DESCRIPTION
**Pull request by no-reply**
Marmottawrapper tasks were previously only added to rails projects,
this adds them to environments where Rake exists, but Rails does not.

### CODE REVIEW

**Comment by anarchivist** [comment]
Unless I'm missing something, this shouldn't be necessary, because this is already happening in the `Rakefile` in `marmottawrapper`'s root:

``` shell
halfsour:tmp mark$ bundle gem marmotta-test
      create  marmotta-test/Gemfile
      create  marmotta-test/Rakefile
      create  marmotta-test/LICENSE.txt
      create  marmotta-test/README.md
      create  marmotta-test/.gitignore
      create  marmotta-test/marmotta-test.gemspec
      create  marmotta-test/lib/marmotta/test.rb
      create  marmotta-test/lib/marmotta/test/version.rb
Initializing git repo in /private/tmp/marmotta-test
halfsour:tmp mark$ cd mar
marmotta/      marmotta-test/ 
halfsour:tmp mark$ cd marmotta-test/
halfsour:marmotta-test mark$ cat >> Rakefile 
require 'marmottawrapper'
halfsour:marmotta-test mark$ subl .
# add to marmotta-test.gemspec:   spec.add_development_dependency "marmottawrapper", ">= 0.0.5"
halfsour:marmotta-test mark$ bundle
Fetching gem metadata from https://rubygems.org/.............
Resolving dependencies...
Using rake 10.3.2
Using bundler 1.7.3

marmotta-test at /private/tmp/marmotta-test did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  "FIXME" or "TODO" is not a description
Using marmotta-test 0.0.1 from source at .
Using marmottawrapper 0.0.5
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
halfsour:marmotta-test mark$ rake -T
rake build             # Build marmotta-test-0.0.1.gem into the pkg directory
rake install           # Build and install marmotta-test-0.0.1.gem into sys...
rake marmotta:clean    # remove the Marmotta data directory and recreate it
rake marmotta:fetch    # fetch the Marmotta and Tomcat distribution
rake marmotta:install  # Install the Marmotta and Tomcat distribution
rake marmotta:restart  # Restart Marmotta/Tomcat
rake marmotta:start    # Start Marmotta/Tomcat
rake marmotta:stop     # Stop Marmotta/Tomcat
rake release           # Create tag v0.0.1 and build and push marmotta-test...
```

**Comment by anarchivist** [comment]
Line in question: https://github.com/dpla/marmottawrapper/blob/develop/Rakefile#L6

**Comment by no-reply** [comment]
I get different results when running the commands from your comments:

``` bash
tjohnson@claude:~/src/marmotta-test$ bundle gem marmotta-test
      create  marmotta-test/Gemfile
      create  marmotta-test/Rakefile
      create  marmotta-test/LICENSE.txt
      create  marmotta-test/README.md
      create  marmotta-test/.gitignore
      create  marmotta-test/marmotta-test.gemspec
      create  marmotta-test/lib/marmotta/test.rb
      create  marmotta-test/lib/marmotta/test/version.rb
Initializing git repo in /home/tjohnson/src/marmotta-test/marmotta-test
tjohnson@claude:~/src/marmotta-test$ cd marmotta-test/
tjohnson@claude:~/src/marmotta-test/marmotta-test$ echo "require 'marmottawrapper'" >> Rakefile 
tjohnson@claude:~/src/marmotta-test/marmotta-test$ emacs marmotta-test.gemspec 
# add spec.add_dependency "marmottawrapper", "~> 0.0.5"
tjohnson@claude:~/src/marmotta-test/marmotta-test$ bundle
Fetching gem metadata from https://rubygems.org/.............
Resolving dependencies...
Using rake 10.3.2
Using bundler 1.6.3
Using marmottawrapper 0.0.5

marmotta-test at /home/tjohnson/src/marmotta-test/marmotta-test did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  "FIXME" or "TODO" is not a description
Using marmotta-test 0.0.1 from source at .
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
tjohnson@claude:~/src/marmotta-test/marmotta-test$ bundle exec rake -T
rake build    # Build marmotta-test-0.0.1.gem into the pkg directory
rake install  # Build and install marmotta-test-0.0.1.gem into system gems
rake release  # Create tag v0.0.1 and build and push marmotta-test-0.0.1.gem to Rubygems
```

I wonder whether you're installing the branch?  I don't think Rakefile is being called at any point, simply by requiring marmottawrapper; the Marmottawrapper class is

**Comment by anarchivist** [comment]
Yeah, sorry. Another instance of my brain failing me when I'm under the weather. I think this is ready to merge, and maybe it's time we cut a release for 0.0.6.

**Pull request merged**
